const PRODUCT_DATA = [
  {
    id: "card1",
    title: `Starting ₹99 | All your home improvement needs`,
    thumbnails: [
      "/src/assets/images/@starts_at_99/01.png",
      "/src/assets/images/@starts_at_99/02.png",
      "/src/assets/images/@starts_at_99/03.png",
      "/src/assets/images/@starts_at_99/04.png",
    ],
    thumbnails_title: [
      "Spin mops, wipes & more",
      "Bathroom hardware & accessories",
      "Hammers, screwdrivers & more",
      "Extension boards, plugs & more",
    ],
    open_link_text: "Explore all",
  },
  {
    id: "card2",
    title: `Up to 60% off | Styles for men`,
    thumbnails: [
      "./src/assets/images/men_style/01.png",
      "./src/assets/images/men_style/02.png",
      "./src/assets/images/men_style/03.png",
      "./src/assets/images/men_style/04.png",
    ],
    thumbnails_title: ["Clothing", "Footwear", "Watches", "Bags & wallets"],
    open_link_text: "End of season sale",
  },
  {
    id: "card3",
    title: `Up to 75% off | Headphones`,
    thumbnails: [
      "./src/assets/images/headphone_brands/01.png",
      "./src/assets/images/headphone_brands/02.png",
      "./src/assets/images/headphone_brands/03.png",
      "./src/assets/images/headphone_brands/04.png",
    ],
    thumbnails_title: [
      "Up to 75% off I boAt",
      "Up to 75% Off I boult",
      "Up to 75% off I Noise",
      "Up to 75% Off I Zebronics",
    ],
    open_link_text: "See all offers",
  },
  {
    id: "card4",
    title: `Revamp your home in style`,
    thumbnails: [
      "/src/assets/images/home_style/01.png",
      "/src/assets/images/home_style/02.png",
      "/src/assets/images/home_style/03.png",
      "/src/assets/images/home_style/04.png",
    ],
    thumbnails_title: [
      "Spin mops, wipes & more",
      "Bathroom hardware & accessories",
      "Hammers, screwdrivers & more",
      "Extension boards, plugs & more",
    ],
    open_link_text: "See more",
  },
  {
    id: "card5",
    title: `Appliances for your home | Up to 55% off`,
    thumbnails: [
      "/src/assets/images/home_appliance/01.png",
      "/src/assets/images/home_appliance/02.png",
      "/src/assets/images/home_appliance/03.png",
      "/src/assets/images/home_appliance/04.png",
    ],
    thumbnails_title: [
      "Air conditioners",
      "Refrigerators",
      "Microwaves",
      "Washing machines",
    ],
    open_link_text: "See more",
  },
  {
    id: "card6",
    title: `Appliances for your home | Up to 55% off`,
    thumbnails: [
      "/src/assets/images/home_appliance/01.png",
      "/src/assets/images/home_appliance/02.png",
      "/src/assets/images/home_appliance/03.png",
      "/src/assets/images/home_appliance/04.png",
    ],
    thumbnails_title: [
      "Air conditioners",
      "Refrigerators",
      "Microwaves",
      "Washing machines",
    ],
    open_link_text: "See more",
  },
  {
    id: "card7",
    title: `Starting ₹199 | Amazon brands & more`,
    thumbnails: [
      "/src/assets/images/amazon_brands_&_more/01.png",
      "/src/assets/images/amazon_brands_&_more/02.png",
      "/src/assets/images/amazon_brands_&_more/03.png",
      "/src/assets/images/amazon_brands_&_more/04.png",
    ],
    thumbnails_title: [
      `Professional tools`,
      `Measuring instruments`,
      `Cleaning supplies`,
      `Medical supplies`,
    ],
    open_link_text: "See more",
  },
  {
    id: "card8",
    title: "Today's Deals",
    thumbnails: [
      "./src/assets/images/today's_deals/01.png",
      "./src/assets/images/today's_deals/02.png",
      "./src/assets/images/today's_deals/03.png",
      "./src/assets/images/today's_deals/04.png",
      "./src/assets/images/today's_deals/05.png",
      "./src/assets/images/today's_deals/06.png",
      "./src/assets/images/today's_deals/07.png",
      "./src/assets/images/today's_deals/08.png",
      "./src/assets/images/today's_deals/09.png",
      "./src/assets/images/today's_deals/10.png",
      "./src/assets/images/today's_deals/11.png",
      "./src/assets/images/today's_deals/12.png",
      "./src/assets/images/today's_deals/13.png",
      "./src/assets/images/today's_deals/14.png",
      "./src/assets/images/today's_deals/15.png",
    ],
    offers: [
      "Up to 25% off",
      "Up to 53% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 45% off",
      "Up to 47% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 85% off",
      "Up to 27% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 91% off",
      "Up to 10% off",
    ],
    thumbnails_title: [
      "Great Deals on Health and Sports Supplements",
      "Cookware, Pots & Pans from Top Brands",
      "Travel Adapters And Electronic Accessories from RTS",
      "Best Deals on Asian",
      "Great Offers on Creatine suppliments by MuscleBlaze",
      "Dinnerware & Serveware from Top Brands",
      "Bath hardware accessories from Fortune",
      "Bath hardware accessories and Curtain Brackets",
      "Amazing Best Deals by MALENO",
      "Amazing Best Deals by BULLMER",
      "Amazing Best Deals by Juari",
      "Kitchen Jars and Storage from Top Brands",
      "arc Loire, Monrow and More",
      "Dinnerware & Serveware from Top Brands",
      "Wallpapers Starting 149 from wolpin",
      // "Cooking and Cutting Tools from Top Brands"
    ],
    open_link_text: "see all deals",
  },
  {
    id: "card9",
    title: "Kitchen essentials I Amazon Brands & more",
    thumbnails: [
      "./src/assets/images/kitchen_essentials/01.png",
      "./src/assets/images/kitchen_essentials/02.png",
      "./src/assets/images/kitchen_essentials/03.png",
      "./src/assets/images/kitchen_essentials/04.png",
      "./src/assets/images/kitchen_essentials/05.png",
      "./src/assets/images/kitchen_essentials/06.png",
      "./src/assets/images/kitchen_essentials/07.png",
      "./src/assets/images/kitchen_essentials/08.png",
      "./src/assets/images/kitchen_essentials/09.png",
      "./src/assets/images/kitchen_essentials/10.png",
      "./src/assets/images/kitchen_essentials/11.png",
      "./src/assets/images/kitchen_essentials/12.png",
      "./src/assets/images/kitchen_essentials/13.png",
      "./src/assets/images/kitchen_essentials/14.png",
      "https://m.media-amazon.com/images/I/31waf7QrgYL._AC_SY200_.jpg",
    ],
    offers: [
      "Up to 25% off",
      "Up to 53% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 45% off",
      "Up to 47% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 85% off",
      "Up to 27% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 91% off",
      "Up to 10% off",
    ],
    thumbnails_title: [
      "Great Deals on Health and Sports Supplements",
      "Cookware, Pots & Pans from Top Brands",
      "Travel Adapters And Electronic Accessories from RTS",
      "Best Deals on Asian",
      "Great Offers on Creatine suppliments by MuscleBlaze",
      "Dinnerware & Serveware from Top Brands",
      "Bath hardware accessories from Fortune",
      "Bath hardware accessories and Curtain Brackets",
      "Amazing Best Deals by MALENO",
      "Amazing Best Deals by BULLMER",
      "Amazing Best Deals by Juari",
      "Kitchen Jars and Storage from Top Brands",
      "arc Loire, Monrow and More",
      "Dinnerware & Serveware from Top Brands",
      "Wallpapers Starting 149 from wolpin",
      // "Cooking and Cutting Tools from Top Brands"
    ],
    open_link_text: "See all deals",
  },
  {
    id: "card10",
    title: `Up to 65% off | Deals on wide range of TVs`,
    thumbnails: [
      "/src/assets/images/wise-range-tv/01.jpg",
      "/src/assets/images/wise-range-tv/02.jpg",
      "/src/assets/images/wise-range-tv/03.jpg",
      "/src/assets/images/wise-range-tv/04.jpg",
    ],
    thumbnails_title: [
      "Budget TVs | Starting ₹5,999",
      "4K TVs | Up to 18 months No Cost EMI",
      "Big Screens | Save upto ₹30,000",
      "Ultra Premium TVs | Flat off",
    ],
    open_link_text: "See all deals",
  },
  {
    id: "card11",
    title: `Minimum 60% off | Deals on top brands`,
    thumbnails: [
      "/src/assets/images/top-brands-off/01.jpg",
      "/src/assets/images/top-brands-off/02.jpg",
      "/src/assets/images/top-brands-off/03.jpg",
      "/src/assets/images/top-brands-off/04.jpg",
    ],
    thumbnails_title: [
      `Tops & tees`,
      `Kurtas & kurtis`,
      "Dresses & jumpsuits",
      "sarees",
    ],
    open_link_text: "See all deals",
  },
  {
    id: "card12",
    title: `Appliances for your home | Up to 55% off`,
    thumbnails: [
      "/src/assets/images/home_appliance/01.png",
      "/src/assets/images/home_appliance/02.png",
      "/src/assets/images/home_appliance/03.png",
      "/src/assets/images/home_appliance/04.png",
    ],
    thumbnails_title: [
      "Air conditioners",
      "Refrigerators",
      "Microwaves",
      "Washing machines",
    ],
    open_link_text: "See more",
  },
  {
    id: "card13",
    title: `Birthday store`,
    thumbnails: [
      "/src/assets/images/birthday-gift/01.png",
      "/src/assets/images/birthday-gift/02.png",
      "/src/assets/images/birthday-gift/03.png",
      "/src/assets/images/birthday-gift/04.png",
    ],
    thumbnails_title: [
      "Gift for Women",
      "Gift for men",
      "Gift for Boys",
      "Gift for Girls",
     
    ],
    open_link_text: "See more",
  },
  {
    id:"card14",
    title: "new series CRUSHED",
    thumbnails: ['/src/assets/images/crushed-series-thumbnail.jpeg']
  },
  {
    id: "card15",
    title: "Today's Deals",
    thumbnails: [
      "./src/assets/images/today's_deals/07.png",
      "./src/assets/images/today's_deals/02.png",
      "./src/assets/images/today's_deals/03.png",
      "./src/assets/images/today's_deals/04.png",
      "./src/assets/images/today's_deals/05.png",
      "./src/assets/images/today's_deals/06.png",
      "./src/assets/images/today's_deals/07.png",
      "./src/assets/images/today's_deals/08.png",
      "./src/assets/images/today's_deals/09.png",
      "./src/assets/images/today's_deals/10.png",
      "./src/assets/images/today's_deals/11.png",
      "./src/assets/images/today's_deals/12.png",
      "./src/assets/images/today's_deals/13.png",
      "./src/assets/images/today's_deals/14.png",
      "./src/assets/images/today's_deals/15.png",
    ],
    offers: [
      "Up to 25% off",
      "Up to 53% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 45% off",
      "Up to 47% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 47% off",
      "Up to 85% off",
      "Up to 27% off",
      "Up to 25% off",
      "Up to 95% off",
      "Up to 91% off",
      "Up to 10% off",
    ],
    thumbnails_title: [
      "Great Deals on Health and Sports Supplements",
      "Cookware, Pots & Pans from Top Brands",
      "Travel Adapters And Electronic Accessories from RTS",
      "Best Deals on Asian",
      "Great Offers on Creatine suppliments by MuscleBlaze",
      "Dinnerware & Serveware from Top Brands",
      "Bath hardware accessories from Fortune",
      "Bath hardware accessories and Curtain Brackets",
      "Amazing Best Deals by MALENO",
      "Amazing Best Deals by BULLMER",
      "Amazing Best Deals by Juari",
      "Kitchen Jars and Storage from Top Brands",
      "arc Loire, Monrow and More",
      "Dinnerware & Serveware from Top Brands",
      "Wallpapers Starting 149 from wolpin",
      // "Cooking and Cutting Tools from Top Brands"
    ],
    
    open_link_text: "see all deals",
  },
  {
    id:"card16",
    title: "15% off on Flight Tickets",
    thumbnails: ['/src/assets/images/flight_tickets_off_thumbnail.jpg']
  },
];
export default PRODUCT_DATA;
